name: Publish package on NuGet

on:
  push:
    tags:
    - '*'

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Pack
      run: dotnet pack **/NUnit.OneTimeSetup.DreddLogs.csproj --nologo -o artifacts
    - name: Publish on NuGet
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --no-symbols --skip-duplicate